language: c

compiler:
  - gcc
  - clang

dist: bionic

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: linux
      arch: ppc64le

addons:
  apt:
    update: true
    packages:
    - build-essential
    - fakeroot
    - debhelper
    - libtool
    - libtool-bin
    - liblua5.1-dev
    - lua5.1

script:
  # Build the package.
  - (cd pkg && make deb)
  # Compile and run the tests.
  - (cd src && make clean && DEBUG=1 make tests)
  # Install the DEB packages and run the Lua tests.
  #- (sudo dpkg -i *.deb && cd src/lua && lua ./t_lpm.lua)
